### ISSUE TITLE
How to train ? 

### ISSUE THREAD

**Issue by WestbrookZero** [AryaRajivChaloli/Audio-Emotion-Recognition#17]

**Comment by nekarc** [comment]
You may currently use the model that we have trained which is present in the [DEMO](https://github.com/AryaRajivChaloli/Audio-Emotion-Recognition/tree/master/DEMO) folder.
We shall get back to you regarding the details on how to replicate the training model soon.

**Comment by GreeshmaKaranth** [comment]
Hi @WestbrookZero! The python code that runs all modules can be found in code/4_finalModel/3_finalModels.ipynb. Running this file on the data can replicate the results that we achieved. Hope this helped! All the best! :)
